version: 1.0.{build}
image: Visual Studio 2015
environment:
  PYTHON37_LOCATION: C:\Python37
  QT_DIR: C:\Qt\5.9.5\mingw53_32
  PATH: '%PATH%;%QT_DIR%\bin;C:\MinGW\bin'
build_script:
- cmd: >-
    echo %PATH%

    qmake PyRun.pro

    mingw32-make

    dir C:\projects\expresspython\

    dir C:\projects\expresspython\release

    windeployqt C:\projects\expresspython\release\expressPython.exe

    del /S C:\projects\expresspython\release\*.o

    del /S C:\projects\expresspython\release\*.cpp

    xcopy /e /v C:\Python37 C:\projects\expresspython\release

    7z a expressPython.7z C:\projects\expresspython\release
test: off
artifacts:
  - path: expressPython.7z
    name: expressPython