version: 1.0.{build}
image: Visual Studio 2015
environment:
  PYTHON37_LOCATION: C:\Python37
  QT_DIR: C:\Qt\5.9\mingw53_32
  PATH: '%PATH%;%QT_DIR%\bin;C:\MinGW\bin'
build_script:
- cmd: >-
    echo %PATH%

    C:\Qt\5.9\mingw53_32\bin\qmake.exe PyRun.pro

    C:\MinGW\bin\mingw32-make.exe

    dir C:\projects\expresspython\

    dir C:\projects\expresspython\release

    copy C:\projects\expresspython\README.md C:\projects\expresspython\release\README.md

    C:\Qt\5.9\mingw53_32\bin\windeployqt.exe C:\projects\expresspython\release\expressPython.exe

    del /S C:\projects\expresspython\release\*.o

    del /S C:\projects\expresspython\release\*.cpp

    del /S C:\projects\expresspython\release\*.h

    C:\Python37\python.exe -m pip install jedi

    xcopy /e /v C:\Python37 C:\projects\expresspython\release

    7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on expressPython.7z C:\projects\expresspython\release\*
test: off
artifacts:
  - path: expressPython.7z
    name: expressPython
